### ISSUE TITLE
DateRangeSelector cannot select "disabled" dates of other months

### ISSUE THREAD

**Issue by jrmyio** [timelessco/renderlesskit-react#220]
Going by this example:
https://renderlesskit-react.vercel.app/?path=/story/datepicker-range--controlled-input

When you make a selection that uses dates of the "next month", the selection looks like you can select it:
![image](https://user-images.githubusercontent.com/971199/132821154-70f40df6-a4b8-47f2-99ec-c11caaa12269.png)

However because these dates are "disabled" you cannot actually left-click to confirm the selection.

Is there any reason (aside from styling) that dates that are not part of the current month have `aria-disabled=true`?

This also goes for minmax ranges:
https://renderlesskit-react.vercel.app/?path=/story/calendar-range--min-max-date&args=start:2021-09-10;end:2021-09-17

**Comment by navin-moorthy** [comment]
Yeah, it is a mistake done in the styling part, you cannot click the "disabled" dates.

You can however select the dates in the next month after navigating to the next month in the calendar which are within the min/max range.

**Comment by navin-moorthy** [comment]
Fixed in #326
